name: hayrx
on:
  workflow_dispatch: # Позволит вам запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. Скачиваем официальный открытый код плеера VLC
    - name: Clone VLC Source Code
      run: |
        git clone https://videolan.org
        cd vlc-ios

    # 2. Собираем приложение в папку (без платной подписи Apple)
    - name: Build Xcode Project
      run: |
        cd vlc-ios
        xcodebuild -project VLC.xcodeproj -scheme "VLC-iOS" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO

    # 3. Упаковываем результат в готовый .ipa файл для Айфона
    - name: Create IPA Package
      run: |
        mkdir -p Payload
        cp -r vlc-ios/build/Release-iphoneos/VLC.app Payload/
        zip -r vlc-app.ipa Payload
        mv vlc-app.ipa ../

    # 4. Выкладываем готовый файл на GitHub, чтобы вы могли его скачать
    - name: Upload Finished IPA
      uses: actions/upload-artifact@v4
      with:
        name: vlc-ios-application
        path: vlc-app.ipa
